---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-t4s-tkna-net-v1-t4s
  failurePolicy: Fail
  name: vt4s.kb.io
  rules:
  - apiGroups:
    - t4s.tkna.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - t4s
  sideEffects: None
