# permissions for end users to view crons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cron-viewer-role
rules:
- apiGroups:
  - t4s.tkna.net
  resources:
  - crons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - t4s.tkna.net
  resources:
  - crons/status
  verbs:
  - get
