---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tetris.tkna.net
  resources:
  - boards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tetris.tkna.net
  resources:
  - boards/finalizers
  verbs:
  - update
- apiGroups:
  - tetris.tkna.net
  resources:
  - boards/status
  verbs:
  - get
  - patch
  - update
