# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/t4s.tkna.net_boards.yaml
- bases/t4s.tkna.net_t4s.yaml
- bases/t4s.tkna.net_actions.yaml
- bases/t4s.tkna.net_crons.yaml
- bases/t4s.tkna.net_minoes.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_boards.yaml
#- patches/webhook_in_t4s.yaml
#- patches/webhook_in_actions.yaml
#- patches/webhook_in_crons.yaml
#- patches/webhook_in_minoes.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_boards.yaml
#- patches/cainjection_in_t4s.yaml
#- patches/cainjection_in_actions.yaml
#- patches/cainjection_in_crons.yaml
#- patches/cainjection_in_minoes.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
