name: ci
on:
  push:
    branches:
      - '**'
env:
  go-version: 1.19
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - name: docker-build
        run: make docker-build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - name: Lint
        run: make lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - name: Test
        run: make test
  e2e:
    name: End-to-End Tests
    strategy:
      matrix:
        k8s-version: ['1.23.12', '1.24.6', '1.25.2']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go-version }}
    - run: make start KUBERNETES_VERSION=${{ matrix.k8s-version }}
      working-directory: e2e
    - run: make test
      working-directory: e2e
